### ISSUE TITLE
[question] Webpack transform?

### ISSUE THREAD

**Issue by rawrmaan** [gaearon/react-transform-catch-errors#1]
First of all, I love this idea and I've been waiting for it ever since your react-europe talk. But I don't use Babel, I write CJSX with Webpack. Any plans to make this a Webpack transform too? Thanks.

**Comment by gaearon** [comment]
This specific transform is not related neither to Babel nor Webpack. If you look at the source, it's a function that takes a React class and does something with it. Therefore you can use it in any environment as long as _you have a way of finding React classes and wrapping each React class in arbitrary function_.

For Babel, I wrote [babel-plugin-react-transform](https://github.com/gaearon/babel-plugin-react-transform) that does this via static analysis. It is entirely possible to write some kind of Webpack `react-transform-loader` that would attempt to run transforms on everything in `module.exports`, just like React Hot Loader did before. It won't be as powerful as a Babel plugin though: for example, it won't see non-exported classes, or classes inside functions. Another approach is to write CoffeeScript parser for Babel. (I remember Seb saying this is possible.)

Still, this isn't the discussion for this repo, because it's just one specific transform. We can discuss this in [react-transform-boilerplate](https://github.com/gaearon/react-transform-boilerplate) if you'd like.
