### ISSUE TITLE
Doesn't work when used together with babel-plugin-transform-decorators-legacy 

### ISSUE THREAD

**Issue by smashercosmo** [gaearon/react-transform-catch-errors#26]
Yep, I know that both transforms are use-on-your-own-risk kind of thing) But just FYI, these transforms don't work together. You get this error in console:

```
Uncaught TypeError: Cannot set property render of #<ComponentName> which has only a getter
```

removing either babel-plugin-transform-decorators-legacy or react-transform-catch-errors fixes the issue.

**Comment by gaearon** [comment]
Would you like to take a stab at fixing this? I would presume that using `Object.defineProperty` might work instead.

**Comment by smashercosmo** [comment]
The good news is that, yes, it did the trick) The bad news is that I have absolutely no idea, what's going on here :) So, of course I can just submit a PR without digging into this, but it would be awesome if you could give me some hints) Do you have any idea where does this error come from? Why does render property on ReactClass prototype become unwritable?

**Comment by gaearon** [comment]
I would suggest you to refer to [`Object.defineProperty()`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) docs.

> Why does render property on ReactClass prototype become unwritable?

My guess is that some of the decorators you use return a `get` descriptor rather than a `value` property descriptor. (Are you using some decorator for autobinding?) When a property is defined using a `get` descriptor, you can’t use assignment operator on this property. However, unless the descriptor has `configurable: false`, you can redefine this property again with `Object.defineProperty()`. Again, the docs should give you a better idea.

Finally, I wouldn’t recommend using decorators before you have a good idea about how they work. Understanding `Object.defineProperty()` is essential to understanding decorators.

**Comment by smashercosmo** [comment]
Yes, you're right, it's autobind-decorator, that redefines render property. Now I get it. Thank you. I'll submit PR with a fix tomorrow.
